### ISSUE TITLE
interactive card

### ISSUE THREAD

**Issue by blairun** [danishru/wled_liveviewproxy#2]
Many home assistant ui elements can be clicked/tapped by adding standard yaml like this:

```
  tap_action:
    action: navigate
    navigation_path: lights
  double_tap_action:
    action: navigate
    navigation_path: camera
  hold_action:
    action: url
    url_path: https://weather.com
```

It would be great if those options were available in this card.
