### ISSUE TITLE
Previous state

### ISSUE THREAD

**Issue by janhollez** [danishru/wled_liveviewproxy#3]
Is there a way to get the previous state of the light. This way we can use this for a temporary automation when a notification comes in and afterwords revert to the previous setting.

**Comment by danishru** [comment]
Hi @janhollez,

Glad to hear you’re using WLED Live View Proxy! You can achieve a “previous state” by calling the wled_liveviewproxy.send_command service in your automation to save the current state into a WLED preset before your notification, then restore that preset afterward. For details on presets, see the WLED documentation: https://kno.wled.ge/features/presets

There are no plans to add built-in preset or rollback support to this integration at this time.

**Comment by janhollez** [comment]
Thanks @danishru 
this indeed works

For others that wonder how to do it exactly,
first I save the state to preset1
then I load preset2
You can then eventually after a delay load 1 again


```
  - action: wled_liveviewproxy.send_command
    response_variable: ledResult1
    data:
      targets:
        device_id: <deviceId>
      command:
        psave: 1
        "n": previous state
        ib: true
        sb: true
        v: true
  - action: wled_liveviewproxy.send_command
    response_variable: ledResult2
    data:
      targets:
        device_id: <deviceId>
      command:
        ps: 2
```
