### ISSUE TITLE
Tap action for JSON calls not working

### ISSUE THREAD

**Issue by madjetey** [danishru/wled_liveviewproxy#4]
Trying to use a tap action in a template card to call a JSON preset but get the following error:
`The action requires responses and must be called with return_response=True.`

Full template code below:
```
type: entity
show_name: false
show_state: true
show_icon: true
entity: sensor.backup_backup_manager_state
tap_action:
  action: perform-action
  perform_action: wled_liveviewproxy.send_command
  target: {}
  data:
    targets:
      entity_id: light.wlvp_kitchen_counter
    command: ps="1"
```

**Comment by danishru** [comment]
Hi @madjetey,

This limitation—  
> “The action requires responses and must be called with return_response=True”  
—currently can’t be worked around in a Lovelace `tap_action` the same way as direct service calls. (You’ll see the same behavior when calling, for example, `weather.get_forecasts`.)

I may revisit this when Home Assistant exposes more options for returning service responses in UI actions. In the meantime, here’s a **workaround**:

1. **Create a script** in your GUI YAML with the desired parameters and a `response_variable`. For example:
   ```yaml
   alias: "WLED Preset PS=1"
   sequence:
    - service: wled_liveviewproxy.send_command
      data:
        targets:
          entity_id: light.wlvp_kitchen_counter
        command:
          ps: "1"
      response_variable: wled_response
   ```
2. **Call the script** in your `tap_action` instead of the service directly:
   ```yaml
   tap_action:
     action: perform-action
     perform_action: script.wled_preset_ps1
     target: {}
   ```

This way the call is wrapped in a script (which correctly returns a response) and your `tap_action` will succeed without that error.
